# Custom settings
author: Kevin Wellmann
repository: https://github.com/wellmann/wellmann.github.io
title: Kevin Wellmann - Web Developer
description: Hey there, Iâ€™m Kevin a web developer from Germany. My framework of choice is WordPress with which I am building custom tailored solutions.
url: https://kevin.wellmann.io
email: hello@wellmann.io

# Contact buttons
buttons:
  - title: Say hi
    link: mailto:hello@wellmann.io?subject=hi
    
  - title: Github
    link: https://github.com/wellmann
    
  - title: Xing
    link: https://www.xing.com/profile/Kevin_Wellmann
  
  - title: LinkedIn
    link: https://linkedin.com/in/kevin-wellmann-6b7819192

# Handling Reading
safe: true
exclude:
  - node_modules
  - CNAME
  - package.json
  - package-lock.json
  - Vagrantfile

# Plugins
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# SASS
sass:
    sass_dir: assets/css
    style: compressed

# Markdown Processors
kramdown:
  auto_ids: false